In [20]:
import pyarrow as pa
import pyarrow.dataset as ds

In [8]:
help(pa.field)

Help on cython_function_or_method in module pyarrow.lib:

field(name, type=None, nullable=None, metadata=None)
    field(name, type=None, nullable=None, metadata=None)

    Create a pyarrow.Field instance.

    Parameters
    ----------
    name : str or bytes
        Name of the field.
        Alternatively, you can also pass an object that implements the Arrow
        PyCapsule Protocol for schemas (has an ``__arrow_c_schema__`` method).
    type : pyarrow.DataType or str
        Arrow datatype of the field or a string matching one.
    nullable : bool, default True
        Whether the field's values are nullable.
    metadata : dict, default None
        Optional field metadata, the keys and values must be coercible to
        bytes.

    Returns
    -------
    field : pyarrow.Field

    Examples
    --------
    Create an instance of pyarrow.Field:

    >>> import pyarrow as pa
    >>> pa.field('key', pa.int32())
    pyarrow.Field<key: int32>
    >>> pa.field('key', pa.int32(), nullable=False)
    pyarrow.Field<key: int32 not null>

    >>> field = pa.field('key', pa.int32(),
    ...                  metadata={"key": "Something important"})
    >>> field
    pyarrow.Field<key: int32>
    >>> field.metadata
    {b'key': b'Something important'}

    Use the field to create a struct type:

    >>> pa.struct([field])
    StructType(struct<key: int32>)

    A str can also be passed for the type parameter:

    >>> pa.field('key', 'int32')
    pyarrow.Field<key: int32>

In [9]:
partition_fields = [
    pa.field(name = "year", type = pa.int32()),
    pa.field(name = "month", type = pa.int32()),
    pa.field(name = "day", type = pa.int32())
]

pyarrow.Field<year: int32>

In [10]:
data = pa.table({
    "id": [1, 2, 3, 4, 5],
    "value": [10, 20, 30, 40, 50],
    "year": [2026, 2026, 2026, 2026, 2026],
    "month": [7, 7, 7, 7, 7],
    "day": [25, 25, 25, 26, 26]
})

In [19]:
data.to_pandas()

   id  value  year  month  day
0   1     10  2026      7   25
1   2     20  2026      7   25
2   3     30  2026      7   25
3   4     40  2026      7   26
4   5     50  2026      7   26

In [21]:
pa.schema([
    pa.field(name = "year", type = pa.int32()),
    pa.field(name = "month", type = pa.int32()),
    pa.field(name = "day", type = pa.int32())
])

year: int32
month: int32
day: int32

In [25]:
ds.partitioning(pa.schema([
    pa.field(name = "year", type = pa.int32()),
    pa.field(name = "month", type = pa.int32())
]))

In [27]:
ds.partitioning(pa.schema([
    pa.field(name = "year", type = pa.int64()),
    pa.field(name = "month", type = pa.int64())
]))

In [ ]:
import matplotlib.pyplot as plt
import pyecharts

In [1]:
import akshare as ak

ak.stock_fund_flow_individual(symbol = "即时")

  0%|          | 0/104 [00:00<?, ?it/s]

,序号,股票代码,股票简称,最新价,涨跌幅,换手率,流入资金,流出资金,净额,成交额
0,1,688825,长鑫科技,49.00,465.82%,66.40%,848.17亿,564.14亿,284.04亿,1411.87亿
1,2,688496,*ST清越,0.89,20.27%,3.32%,257.98万,434.54万,-176.57万,692.52万
2,3,300534,陇神戎发,13.42,20.04%,26.12%,4.98亿,4.72亿,2562.54万,9.71亿
3,4,300802,矩子科技,22.72,20.02%,9.89%,2.52亿,1.71亿,8133.87万,4.23亿
4,5,301085,亚康股份,61.51,20.00%,12.87%,2.56亿,1.82亿,7333.49万,4.38亿
...,...,...,...,...,...,...,...,...,...,...
5188,5189,603823,百合花,68.32,-10.00%,4.33%,6.37亿,6.50亿,-1275.09万,12.87亿
5189,5190,672,上峰材料,14.02,-10.01%,3.72%,2.76亿,2.38亿,3897.82万,5.14亿
5190,5191,300191,潜能恒信,27.97,-10.90%,12.01%,3.51亿,3.86亿,-3455.68万,7.38亿
5191,5192,300164,通源石油,10.48,-12.23%,27.83%,8.24亿,8.45亿,-2128.40万,16.71亿
5192,5193,301127,武汉天源,15.24,-20.00%,7.98%,4.01亿,4.09亿,-815.42万,8.13亿

In [2]:
ak.stock_fund_flow_industry(symbol="即时")

  0%|          | 0/2 [00:00<?, ?it/s]

,序号,行业,行业指数,行业-涨跌幅,流入资金,流出资金,净额,公司家数,领涨股,领涨股-涨跌幅,当前价
0,1,电子化学品,84668.70,5.41,174.99,159.35,15.64,43,中船特气,15.98,284.94
1,2,元件,21193.60,5.24,346.91,297.13,49.78,62,三环集团,10.64,111.57
2,3,美容护理,4678.00,4.91,14.14,10.94,3.20,33,维琪科技,599.50,155.01
3,4,电池,16970.10,4.89,249.83,212.11,37.73,106,紫建电子,19.99,33.86
4,5,互联网电商,8396.35,4.61,22.44,18.51,3.93,19,华凯易佰,12.39,18.78
...,...,...,...,...,...,...,...,...,...,...,...
85,86,港口航运,1173.54,0.95,26.40,24.98,1.42,36,北部湾港,6.23,12.45
86,87,证券,1453.53,0.71,89.68,88.66,1.01,50,国盛证券,4.11,11.66
87,88,银行,1325.07,0.33,97.51,90.80,6.70,84,沪农商行,1.96,8.34
88,89,保险,2049.25,-0.69,26.12,32.19,-6.07,5,新华保险,0.28,63.30
89,90,油气开采及服务,1612.37,-3.12,34.90,34.62,0.27,19,首华燃气,3.18,20.11

In [4]:
import tushare as ts

pro = ts.pro_api('2faf110684106eec9104a327a18d594d16b8c2c9f027429f5cbb4345')

#获取单日全部股票数据
pro.moneyflow(trade_date='20260727')

,ts_code,trade_date,buy_sm_vol,buy_sm_amount,sell_sm_vol,sell_sm_amount,buy_md_vol,buy_md_amount,sell_md_vol,sell_md_amount,buy_lg_vol,buy_lg_amount,sell_lg_vol,sell_lg_amount,buy_elg_vol,buy_elg_amount,sell_elg_vol,sell_elg_amount,net_mf_vol,net_mf_amount
0,002539.SZ,20260727,114739,12668.78,105436,11647.99,73498,8100.04,81265,8972.64,56818,6265.61,48972,5409.50,10413,1155.77,19795,2160.06,28971,3193.90
1,000791.SZ,20260727,130113,9955.75,106174,8127.53,77253,5908.36,92045,7037.86,48199,3684.93,53558,4096.88,12102,928.46,15891,1215.23,46802,3583.91
2,600577.SH,20260727,365167,26416.31,341897,24729.00,168718,12200.34,162374,11748.57,70384,5090.59,78806,5702.56,8062,584.18,29254,2111.29,35214,2570.61
3,002238.SZ,20260727,38169,2142.20,32351,1813.68,15788,886.64,19184,1077.75,2335,130.37,7257,409.78,2500,142.00,0,0.00,2814,159.64
4,002983.SZ,20260727,9751,1727.64,9788,1735.57,6763,1198.83,7997,1415.96,1124,200.28,670,118.20,817,142.98,0,0.00,4415,786.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5188,002979.SZ,20260727,42301,25165.56,52609,31330.23,40512,24114.72,37495,22316.90,24876,14841.15,19974,11885.36,6003,3578.35,3614,2167.29,167,117.40
5189,603729.SH,20260727,5312,534.43,5075,509.78,4453,447.86,4457,447.97,576,57.58,809,82.13,0,0.00,0,0.00,345,35.84
5190,300945.SZ,20260727,54999,5832.38,45554,4828.78,29030,3072.34,36885,3902.83,9203,973.08,12027,1275.02,1234,128.83,0,0.00,16462,1749.85
5191,603529.SH,20260727,19335,4065.95,19245,4045.69,9354,1967.42,9008,1893.97,3921,823.86,3711,781.52,0,0.00,646,136.05,1390,296.87
5192,300633.SZ,20260727,32411,6057.68,24498,4573.19,14246,2658.87,17621,3292.06,4524,844.79,7474,1401.30,0,0.00,1587,294.80,12287,2299.23

In [ ]:

# #获取单个股票数据
# df = pro.moneyflow(ts_code='002149.SZ', start_date='20190115', end_date='20190315')

In [1]:
6.75 * 20

135.0

In [2]:
349 / 2

174.5